"""Keep public component/dependency references derived from the content kernels.

Narrative plugin documentation stays hand-authored. Only the marked reference
blocks and docs/catalog.md are generated. --check is read-only and fails on drift.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from string import Template
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.daodan.adapter import HOSTS, load_adapter, resolve_support
from scripts.daodan.load import load_plugin
from scripts.daodan.model import INLINE_WORKER_REFERENCE
from scripts.daodan.render import _frontmatter, _unquote

START = "<!-- daodan:reference:start -->"
END = "<!-- daodan:reference:end -->"


def cell(value: str) -> str:
    return " ".join(value.split()).replace("|", "&#124;").replace("<", "&lt;").replace(">", "&gt;")


def code(items) -> str:
    values = []
    for item in items:
        value = cell(str(item))
        values.append(f"<code>{value}</code>" if any(token in str(item) for token in "|<>") else f"`{value}`")
    return ", ".join(values) or "None"


def link(path: Path, destination: Path, label: str | None = None) -> str:
    relative = Path(os.path.relpath(path, destination.parent)).as_posix()
    return f"[{cell(label or path.name)}](<{relative}>)"


def closure(name: str, plugins) -> tuple[list[str], list[str]]:
    local, external = set(), set()

    def visit(current: str):
        if current in local:
            return
        local.add(current)
        for dependency in plugins[current].required_dependencies:
            if dependency in plugins:
                visit(dependency)
            elif "@" in dependency:
                external.add(dependency)
            else:
                raise ValueError(f"{current}: unknown local dependency {dependency}")

    visit(name)
    return sorted(local), sorted(external)


def plugin_links(names, destination: Path, root: Path) -> str:
    return ", ".join(link(root / "docs/plugins" / f"{name}.md", destination, name) for name in names) or "None"


def reference(plugin, plugins, adapters, destination: Path, root: Path) -> str:
    local, external = closure(plugin.name, plugins)
    direct_local = sorted(dep for dep in plugin.required_dependencies if dep in plugins)
    direct_external = sorted(dep for dep in plugin.required_dependencies if dep not in plugins)
    lines = [START, "## Source-derived reference", "",
             "Generated by `python scripts/sync_plugin_docs.py`. Edit the kernel and regenerate",
             "this block; keep explanations above it. `--check` detects stale references.", "",
             f"**Version:** `{plugin.version}`. **Source:** {link(plugin.root / 'plugin.toml', destination, 'plugin.toml')}.", "",
             "### Required dependencies", "",
             "Every listed plugin dependency is mandatory. Transitive requirements remain",
             "mandatory when using this plugin alone. The local closure includes this plugin.", "",
             "| Requirement | Plugins |", "|---|---|",
             f"| Direct local | {plugin_links(direct_local, destination, root)} |",
             f"| Direct external | {code(direct_external)} |",
             f"| Local closure ({len(local)}) | {plugin_links(local, destination, root)} |",
             f"| External closure ({len(external)}) | {code(external)} |", "",
             "External bundles are separate upstream installations, not copied local skills.",
             f"See {link(root / 'docs/hosts.md', destination, 'host setup')} for selection and availability requirements.", "",
             f"**Required capabilities:** {code(plugin.capabilities.required)}.",
             f"**Optional capabilities:** {code(plugin.capabilities.optional)}.",
             "Optional capabilities are host mechanisms, not optional local plugin dependencies.", "",
             "### Registered components", "",
             "Names below are kernel IDs. Host entry points and paths follow the adapter",
             f"mapping in {link(root / 'docs/hosts.md', destination, 'the host reference')}.",
             "The source links carry the complete instructions and accepted arguments.", "",
             "| Kind | ID | Purpose and trigger | Source |", "|---|---|---|---|"]
    for kind, names in (("Skill", plugin.components.skills), ("Role", plugin.components.roles), ("Workflow", plugin.components.workflows)):
        for name in names:
            if kind == "Skill":
                path = plugin.root / "skills" / name / "SKILL.md"
            else:
                path = plugin.root / ("roles" if kind == "Role" else "workflows") / f"{name}.md"
            metadata, _ = _frontmatter(path.read_text(encoding="utf-8"))
            purpose = _unquote(metadata.get("description", ""))
            if not purpose:
                raise ValueError(f"Missing component description: {path}")
            lines.append(f"| {kind} | `{plugin.name}:{name}` | {cell(purpose)} | {link(path, destination, name)} |")
    if not any((plugin.components.skills, plugin.components.roles, plugin.components.workflows)):
        lines.append("| None | None | No registered content components | None |")
    if plugin.workflows:
        lines += ["", "### Workflow contracts", "",
                  "Contracts describe observable outputs; Markdown bodies define decisions,",
                  "flags, safety gates and execution. Declared `invoke` execution is unsupported."]
        for workflow in plugin.workflows:
            path = plugin.root / workflow.entrypoint
            metadata, _ = _frontmatter(path.read_text(encoding="utf-8"))
            schemas = [link(plugin.root / schema, destination, schema.as_posix()) for schema in workflow.contract.schemas]
            for shared in workflow.contract.shared_schemas:
                owner, relative = shared.split("/", 1)
                schemas.append(link(plugins[owner].root / relative, destination, shared))
            workers = set(workflow.dispatch.roles)
            for phase in workflow.phases:
                workers.update(phase.fanout)
                if phase.role:
                    workers.add(phase.role)
                if phase.fanout_from and not phase.role:
                    workers.update(plugin.components.roles)
            if workflow.dispatch.inline_workers:
                workers.add(INLINE_WORKER_REFERENCE)
            normalized_workers = set()
            for worker in workers:
                reference = worker.partition(":")[2] or worker
                normalized_workers.add(reference if "/" in reference else f"{plugin.name}/{reference}")
            workers = normalized_workers
            lines += ["", f"#### `{plugin.name}:{workflow.name}`", "",
                      f"**Arguments:** {code([_unquote(metadata['argument-hint'])]) if metadata.get('argument-hint') else 'See the workflow body.'}", "",
                      "| Contract | Value |", "|---|---|",
                      f"| Inputs | {code(workflow.contract.inputs)} |",
                      f"| Outcomes | {code(workflow.contract.outcomes)} |",
                      f"| Artifacts | {code(workflow.contract.artifacts)} |",
                      f"| Schemas | {', '.join(schemas) or 'None declared'} |",
                      f"| Declared workers | {code(sorted(workers))} |",
                      f"| Composed worker isolation | {'Required' if workflow.dispatch.isolated else 'See phase isolation below'} |",
                      f"| Task-specific isolated workers | {'Allowed through the protocol role' if workflow.dispatch.inline_workers else 'Not declared'} |",
                      f"| Sidecar | {link(plugin.root / 'workflows' / (workflow.name + '.toml'), destination)} |", "",
                      "| Phase | Needs | Dispatch | Isolation | Join | Concurrency |", "|---|---|---|---|---|---|"]
            for phase in workflow.phases:
                dispatch = list(phase.fanout)
                if phase.role:
                    dispatch.append(phase.role)
                if phase.fanout_from:
                    dispatch.append("per item in " + phase.fanout_from)
                lines.append(f"| `{phase.id}` | {code(phase.needs)} | {code(dispatch)} | `{phase.isolation}` | {code([phase.join]) if phase.join else 'None declared'} | `{phase.concurrency}` |")
    lines += ["", "### Host exports", "",
              "Package paths and coordination are derived from the host adapters. `native`",
              "and `adapted` describe bindings, not successful installed-host execution.", "",
              "The selected strategy is an adapter binding even for a flat workflow body.",
              "A dispatch harness is rendered only for declared method workers, task-specific",
              "workers or phase fan-out; the host reference explains the entry artifacts.", "",
              "| Host | Package | Binding | Selected workflow strategy |", "|---|---|---|---|"]
    for host, adapter in adapters.items():
        report = resolve_support(plugin, adapter)
        package = root / adapter.layout["root"] / Template(adapter.layout["plugin_root"]).substitute(plugin=plugin.name)
        strategies = ", ".join(f"`{name}: {strategy}`" for name, strategy in report.workflow_strategies) or "No workflow entry points"
        lines.append(f"| {host} | {link(package, destination, package.relative_to(root).as_posix())} | `{report.state}` | {strategies} |")
    if plugin.contract_exports or plugin.components.policies or plugin.mcp_servers:
        lines += ["", "### Additional shipped contracts and mechanisms", ""]
        for export in plugin.contract_exports:
            lines.append(f"- Exported shared contract: {link(plugin.root / export, destination, export.as_posix())}.")
        for policy in plugin.components.policies:
            lines.append(f"- Neutral policy: {link(plugin.root / 'policies' / (policy + '.toml'), destination, policy)}. Enforcement is documented in the policy and host reference.")
        for server in plugin.mcp_servers:
            lines.append(f"- MCP server `{server.name}`: {code([server.command, *server.args])}. Host registration differs; see the host reference.")
    lines += ["", END]
    return "\n".join(lines)


def catalog(plugins, root: Path) -> str:
    destination = root / "docs/catalog.md"
    lines = ["# Plugin and dependency catalog", "",
             "Generated by `python scripts/sync_plugin_docs.py` from the content kernels.",
             "The per-plugin pages combine hand-authored explanations with checked reference blocks.", "",
             f"{len(plugins)} plugins, {sum(len(p.components.skills) for p in plugins.values())} skills, "
             f"{sum(len(p.components.roles) for p in plugins.values())} roles and "
             f"{sum(len(p.workflows) for p in plugins.values())} workflow entry points.", "",
             "Each workflow becomes the command, prompt or workflow skill supported by its",
             "host. See [host setup and export mapping](hosts.md). Component source links,",
             "arguments, contracts and phase plans live in each plugin reference.", "",
             "All local plugin dependencies are mandatory. Closure counts include the entry",
             "plugin. External closure counts distinct required upstream bundles, not skills,",
             "and do not prove their availability on any installed host. Pi companion packages",
             "are adapter requirements, separate from these kernel dependency counts.", "",
             "| Plugin | Version | Purpose | Skills | Roles | Workflows | Local closure | External closure |",
             "|---|---|---|---:|---:|---:|---:|---:|"]
    for plugin in plugins.values():
        local, external = closure(plugin.name, plugins)
        lines.append(f"| {plugin_links([plugin.name], destination, root)} | `{plugin.version}` | {cell(plugin.description)} | {len(plugin.components.skills)} | {len(plugin.components.roles)} | {len(plugin.workflows)} | {len(local)} | {len(external)} |")
    lines += ["", "## Mandatory dependency edges", "",
              "Direct requirements come from `plugin.toml`. The closure follows local edges",
              "and collects every external requirement reached through those plugins.", "",
              "| Plugin | Direct local | Direct external | Transitive external closure |", "|---|---|---|---|"]
    for plugin in plugins.values():
        _, external = closure(plugin.name, plugins)
        local = sorted(dep for dep in plugin.required_dependencies if dep in plugins)
        upstream = sorted(dep for dep in plugin.required_dependencies if dep not in plugins)
        lines.append(f"| {plugin_links([plugin.name], destination, root)} | {plugin_links(local, destination, root)} | {code(upstream)} | {code(external)} |")
    return "\n".join(lines) + "\n"


def replace_reference(document: str, block: str, path: Path) -> str:
    if START not in document and END not in document:
        return document.rstrip() + "\n\n" + block + "\n"
    if document.count(START) != 1 or document.count(END) != 1 or document.index(START) > document.index(END):
        raise ValueError(f"Invalid reference markers: {path}")
    before, rest = document.split(START, 1)
    _, after = rest.split(END, 1)
    return before + block + after


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report drift without writing")
    args = parser.parse_args(argv)
    try:
        plugins = {p.parent.name: load_plugin(p.parent) for p in sorted((REPO_ROOT / "plugins").glob("*/plugin.toml"))}
        adapters = {host: load_adapter(REPO_ROOT / "adapters", host) for host in HOSTS}
        outputs = {REPO_ROOT / "docs/catalog.md": catalog(plugins, REPO_ROOT)}
        for plugin in plugins.values():
            path = REPO_ROOT / "docs/plugins" / f"{plugin.name}.md"
            if not path.is_file():
                raise ValueError(f"Missing hand-authored plugin page: {path}")
            current = path.read_text(encoding="utf-8")
            outputs[path] = replace_reference(current, reference(plugin, plugins, adapters, path, REPO_ROOT), path)
        drift = [path for path, expected in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != expected]
        for path in drift:
            if args.check:
                print(f"drift: {path.relative_to(REPO_ROOT).as_posix()}")
            else:
                path.write_text(outputs[path], encoding="utf-8", newline="\n")
        if args.check and drift:
            return 1
        print(f"{'Checked' if args.check else 'Updated'} {len(plugins)} plugin references and the dependency catalog ({len(drift)} changed).")
        return 0
    except (OSError, ValueError) as error:
        print(f"Documentation error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
