// The Daodan loader for OpenCode V2. Generated by the Daodan compiler from
// adapters/opencode/templates/index.js; edit that file, never this copy.
//
// OpenCode V2 has no marketplace and no static package format: a package
// reaches it as a plugin whose default export registers what it ships. This
// file is fixed code. Everything plugin-specific lives in the `daodan` key of
// the package.json beside it, which the compiler writes from the rendered tree.
//
// Two rules hold everywhere below. Nothing imports outside Node's standard
// library, because a plugin's dependencies are installed by the host and a
// missing one would disable the whole package. And nothing throws out of setup
// or out of a transform callback, because one plugin failing there can take
// down the host's entire plugin generation, providers included.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const TAG = "[daodan]";
const PLUGIN_ROOT = /<plugin-root>/g;
const PACKAGE_ROOT = /<package-root>/g;
// The same tokenizer V2 uses for command arguments
// (core/src/config/plugin/command.ts): images, quoted strings, bare words.
const ARGUMENT = /(?:\[Image\s+\d+\]|"[^"]*"|'[^']*'|[^\s"']+)/gi;
const POSITIONAL = /\$(\d+)/g;

const forward = (value) => value.replaceAll("\\", "/");

/** Replace both root markers with absolute, forward-slashed paths. */
export function substituteRoot(text, pluginRoot, packageRoot) {
  return text
    .replace(PLUGIN_ROOT, () => forward(pluginRoot))
    .replace(PACKAGE_ROOT, () => forward(packageRoot));
}

/**
 * Expand a command template the way V2 expands its own command files.
 *
 * A line-for-line port of `evaluateTemplate` in V2's
 * core/src/config/plugin/command.ts, without its `!`shell`` blocks, which no
 * kernel uses. Quotes group words and are removed. `$N` takes argument N,
 * except the highest placeholder present, which takes argument N and
 * everything after it. Missing positions become empty. `$ARGUMENTS` is the
 * input exactly as typed. With no placeholder at all, a non-blank input is
 * appended after a blank line. The result is trimmed.
 */
export function expandTemplate(template, input) {
  const value = input ?? "";
  const args = (value.match(ARGUMENT) ?? []).map((item) => item.replace(/^["']|["']$/g, ""));
  const placeholders = template.match(POSITIONAL) ?? [];
  const last = Math.max(0, ...placeholders.map((item) => Number(item.slice(1))));
  const expanded = template.replace(POSITIONAL, (_, digits) => {
    const position = Number(digits);
    const index = position - 1;
    if (index >= args.length) return "";
    if (position === last) return args.slice(index).join(" ");
    return args[index];
  });
  const withArguments = expanded.replaceAll("$ARGUMENTS", () => value);
  if (placeholders.length === 0 && !template.includes("$ARGUMENTS") && value.trim()) {
    return `${withArguments}\n\n${value}`.trim();
  }
  return withArguments.trim();
}

/**
 * Which plugins to register, given the user's options.
 *
 * Every dependency inside this marketplace is mandatory, so a selection always
 * brings its transitive closure and an exclusion never removes a plugin a
 * selected one depends on. Both overrides are logged rather than silent.
 */
export function resolveSelection(manifest, options = {}) {
  const plugins = manifest.plugins ?? {};
  const known = Object.keys(plugins).sort();
  const log = [];
  const asList = (value) => (Array.isArray(value) ? value.filter((item) => typeof item === "string") : []);
  const check = (names, label) =>
    names.filter((name) => {
      if (plugins[name]) return true;
      log.push(`${TAG} unknown plugin "${name}" in options.${label}; ignored`);
      return false;
    });

  const requested = check(asList(options.plugins), "plugins");
  // A selection with no recognized name loads everything rather than nothing,
  // so a typo never switches the whole marketplace off.
  if (asList(options.plugins).length && !requested.length) {
    log.push(`${TAG} options.plugins names no known plugin; loading every plugin`);
  }
  const roots = requested.length ? requested : known;
  const requiredBy = new Map();
  const selected = new Set();
  const visit = (name, parent) => {
    if (selected.has(name)) return;
    selected.add(name);
    if (parent) requiredBy.set(name, parent);
    for (const dependency of plugins[name].dependencies ?? []) {
      if (plugins[dependency]) visit(dependency, name);
    }
  };
  for (const name of roots) visit(name, null);
  if (requested.length) {
    for (const [name, parent] of requiredBy) {
      if (!requested.includes(name)) log.push(`${TAG} loading "${name}", required by ${parent}`);
    }
  }

  // Exclusions are resolved together, to a fixed point, so their order never
  // matters: a plugin stays only while something that is itself staying needs it.
  const excluded = new Set(check(asList(options.exclude), "exclude").filter((name) => selected.has(name)));
  const kept = new Map();
  let changed = true;
  while (changed) {
    changed = false;
    for (const name of excluded) {
      const dependents = [...selected].filter(
        (other) =>
          other !== name &&
          (!excluded.has(other) || kept.has(other)) &&
          (plugins[other].dependencies ?? []).includes(name),
      );
      if (dependents.length && !kept.has(name)) {
        kept.set(name, dependents.sort());
        changed = true;
      }
    }
  }
  for (const name of excluded) {
    if (kept.has(name)) {
      log.push(`${TAG} keeping "${name}" despite options.exclude: required by ${kept.get(name).join(", ")}`);
    } else {
      selected.delete(name);
    }
  }
  return { selected: [...selected].sort(), log };
}

function stripFrontmatter(text) {
  const normalized = text.replace(/\r\n/g, "\n");
  if (!normalized.startsWith("---\n")) return normalized;
  const end = normalized.indexOf("\n---\n", 4);
  return end === -1 ? normalized : normalized.slice(end + 5);
}

function readManifest(directory) {
  try {
    const document = JSON.parse(fs.readFileSync(path.join(directory, "package.json"), "utf8"));
    const manifest = document?.daodan;
    if (!manifest || typeof manifest.plugins !== "object") {
      console.error(`${TAG} package.json has no daodan manifest; nothing registered`);
      return null;
    }
    return manifest;
  } catch (error) {
    console.error(`${TAG} cannot read the package manifest; nothing registered:`, error?.message ?? error);
    return null;
  }
}

function guarded(label, action) {
  try {
    action();
  } catch (error) {
    console.error(`${TAG} ${label} skipped:`, error?.message ?? error);
  }
}

async function transform(domain, label, callback) {
  if (!domain || typeof domain.transform !== "function") return;
  try {
    await domain.transform((editor) => guarded(label, () => callback(editor)));
  } catch (error) {
    console.error(`${TAG} ${label} registration failed:`, error?.message ?? error);
  }
}

/** A V2 setup function bound to one package directory. */
export function createLoader(directory) {
  return async function setup(ctx) {
    try {
      const manifest = readManifest(directory);
      if (!manifest) return;
      const { selected, log } = resolveSelection(manifest, ctx?.options ?? {});
      for (const line of log) console.error(line);

      const packageRoot = directory;
      const plugins = selected.map((name) => {
        const entry = manifest.plugins[name];
        const root = path.join(directory, entry.root);
        const read = (file) => substituteRoot(fs.readFileSync(path.join(root, file), "utf8"), root, packageRoot);
        return { name, entry, root, read };
      });

      await transform(ctx.skill, "skills", (editor) => {
        for (const { entry, root, read } of plugins) {
          for (const skill of entry.skills ?? []) {
            guarded(`skill ${skill.id}`, () =>
              editor.add({
                id: skill.id,
                name: skill.name,
                ...(skill.description ? { description: skill.description } : {}),
                path: path.join(root, skill.file),
                content: stripFrontmatter(read(skill.file)),
              }),
            );
          }
        }
      });

      await transform(ctx.agent, "agents", (editor) => {
        for (const { entry, root, read } of plugins) {
          for (const agent of entry.agents ?? []) {
            guarded(`agent ${agent.id}`, () => {
              const system = stripFrontmatter(read(agent.file));
              const permissions = (agent.permissions ?? []).map((rule) => ({
                ...rule,
                resource: substituteRoot(rule.resource, root, packageRoot),
              }));
              // A list that opens with a deny-all is a restriction and replaces
              // whatever the agent had. Anything else is an addition to V2's
              // defaults, which `update` has already put in place for a new ID.
              const restricts = permissions[0]?.action === "*" && permissions[0]?.effect === "deny";
              editor.update(agent.id, (item) => {
                item.mode = "subagent";
                item.description = agent.description;
                item.system = system;
                item.permissions = restricts ? permissions : [...(item.permissions ?? []), ...permissions];
              });
            });
          }
        }
      });

      await transform(ctx.command, "commands", (editor) => {
        for (const { entry, read } of plugins) {
          for (const command of entry.commands ?? []) {
            guarded(`command ${command.name}`, () =>
              editor.add({
                name: command.name,
                ...(command.description ? { description: command.description } : {}),
                execute: async (input) => {
                  const template = stripFrontmatter(read(command.file)).trim();
                  const text = expandTemplate(template, input?.prompt?.text ?? "");
                  await ctx.session.prompt({
                    ...input.prompt,
                    sessionID: input.sessionID,
                    text,
                    delivery: input.delivery,
                  });
                },
              }),
            );
          }
        }
      });

      await transform(ctx.mcp, "mcp servers", (editor) => {
        for (const { entry, root } of plugins) {
          for (const server of entry.mcp ?? []) {
            guarded(`mcp server ${server.name}`, () => {
              if (editor.get?.(server.name)) {
                console.error(`${TAG} mcp server "${server.name}" is already configured; left as it is`);
                return;
              }
              editor.set(server.name, {
                type: "local",
                command: server.command.map((part) => substituteRoot(part, root, packageRoot)),
              });
            });
          }
        }
      });
    } catch (error) {
      console.error(`${TAG} setup failed:`, error?.message ?? error);
    }
  };
}

export default {
  id: "daodan",
  setup: createLoader(path.dirname(fileURLToPath(import.meta.url))),
};
